const typewriterEN = new Typewriter('#typewriterEN', {
	loop: true,
});

typewriterEN.typeString('I am <span style="color: #00abe9;">an engineer.</span>')
      .pauseFor(1000)
	  .deleteChars(12)
	  .typeString('<span style="color: #00abe9;">a SCUBA instructor.</span>')
	  .pauseFor(1000)
	  .deleteChars(19)
	  .typeString('<span style="color: #00abe9;">a drone pilot.</span>')
	  .pauseFor(1000)
	  .deleteChars(14)
	  .typeString('<span style="color: #00abe9;">a tech passionate.</span>')
	  .pauseFor(1000)
	  .deleteChars(18)
	  .typeString('<span style="color: #00abe9;">a creative.</span>')
	  .pauseFor(1000)
	  .deleteChars(11)
	  .typeString('<span style="color: #00abe9;">an ultra-runner.</span>')
	  .pauseFor(1000)
	  .deleteChars(16)
	  .typeString('<span style="color: #00abe9;">a guitar player.</span>')
	  .pauseFor(1000)
	  .deleteChars(16)
	  .typeString('<span style="color: #00abe9;">a human being.</span>')
	  .pauseFor(1000)
      .deleteAll(14)
	  .typeString('I love <span style="color: #00abe9;">solving problems.</span>')
	  .pauseFor(1000)
	  .deleteChars(17)
	  .typeString('<span style="color: #00abe9;">science.</span>')
	  .pauseFor(1000)
	  .deleteChars(8)
	  .typeString('<span style="color: #00abe9;">data analysis.</span>')
	  .pauseFor(1000)
	  .deleteChars(14)
	  .typeString('<span style="color: #00abe9;">automating boring stuff.</span>')
	  .pauseFor(1000)
	  .deleteChars(24)
	  .typeString('<span style="color: #00abe9;">learning.</span>')
	  .pauseFor(1000)
	  .deleteChars(9)
	  .typeString('<span style="color: #00abe9;">to simplify.</span>')
	  .pauseFor(1000)
	  .deleteChars(12)
	  .typeString('<span style="color: #00abe9;">to teach.</span>')
	  .pauseFor(1000)
	  .deleteChars(9)
	  .typeString('<span style="color: #00abe9;">playing sports.</span>')
	  .pauseFor(1000)
	  .deleteChars(16)
	  .typeString('<span style="color: #00abe9;">to fly.</span>')
	  .pauseFor(1000)
	  .deleteChars(7)
	  .typeString('<span style="color: #00abe9;">photography.</span>')
	  .pauseFor(1000)
	  .deleteChars(12)
	  .typeString('<span style="color: #00abe9;">animals.</span>')
	  .pauseFor(1000)
	  .deleteChars(8)
	  .typeString('<span style="color: #00abe9;">nature.</span>')
	  .pauseFor(1000)
	  .deleteAll(15)
      .start();
