const typewriterIT = new Typewriter('#typewriterIT', {
	loop: true,
});

typewriterIT.typeString('Sono <span style="color: #00abe9;">un ingegnere.</span>')
      .pauseFor(1000)
	  .deleteChars(13)
	  .typeString('<span style="color: #00abe9;">un istruttore subacqueo.</span>')
	  .pauseFor(1000)
	  .deleteChars(24)
	  .typeString('<span style="color: #00abe9;">appassionato di tecnologia.</span>')
	  .pauseFor(1000)
	  .deleteChars(27)
	  .typeString('<span style="color: #00abe9;">creativo.</span>')
	  .pauseFor(1000)
	  .deleteChars(9)
	  .typeString('<span style="color: #00abe9;">un ultra-runner.</span>')
	  .pauseFor(1000)
	  .deleteChars(16)
	  .typeString('<span style="color: #00abe9;">un chitarrista.</span>')
	  .pauseFor(1000)
	  .deleteChars(15)
	  .typeString('<span style="color: #00abe9;">un essere umano.</span>')
	  .pauseFor(1000)
      .deleteAll(15)
	  .typeString('Amo <span style="color: #00abe9;">risolvere problemi.</span>')
	  .pauseFor(1000)
	  .deleteChars(19)
	  .typeString('<span style="color: #00abe9;">analizzare dati.</span>')
	  .pauseFor(1000)
	  .deleteChars(16)
	  .typeString('<span style="color: #00abe9;">automatizzare cose noiose.</span>')
	  .pauseFor(1000)
	  .deleteChars(26)
	  .typeString('<span style="color: #00abe9;">imparare.</span>')
	  .pauseFor(1000)
	  .deleteChars(9)
	  .typeString('<span style="color: #00abe9;">semplificare.</span>')
	  .pauseFor(1000)
	  .deleteChars(13)
	  .typeString('<span style="color: #00abe9;">insegnare.</span>')
	  .pauseFor(1000)
	  .deleteChars(10)
	  .typeString('<span style="color: #00abe9;">fare sport.</span>')
	  .pauseFor(1000)
	  .deleteChars(11)
	  .typeString('<span style="color: #00abe9;">volare.</span>')
	  .pauseFor(1000)
	  .deleteChars(7)
	  .typeString('<span style="color: #00abe9;">la fotografia.</span>')
	  .pauseFor(1000)
	  .deleteChars(14)
	  .typeString('<span style="color: #00abe9;">gli animali.</span>')
	  .pauseFor(1000)
	  .deleteChars(12)
	  .typeString('<span style="color: #00abe9;">la natura.</span>')
	  .pauseFor(1000)
	  .deleteAll(15)
      .start();